backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "assets/img"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    extension:
      - md
      - markdown
      - html
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "about/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"

      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "about_us"
    label: "About Us"
    folder: "about_us/"
    create: true
  - name: "dispatches"
    label: "Dispatches"
    folder: "dispatches/"
  - name: "policies_practices"
    label: "Policies and practices"
    folder: "policies_practices/"
  - name: "using_our_library"
    label: "Using our Library"
    folder: "using_our_library/"
  - name: "what_we_have"
    label: "What We Have"
    folder: "what_we_have/"
